#!/usr/bin/env node
import { existsSync, readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { collectStats } from './collect-stats.js';

const root = resolve(new URL('..', import.meta.url).pathname);
const stats = collectStats();
const bundlePath = resolve(root, 'index.html');

if (existsSync(bundlePath)) {
  const html = readFileSync(bundlePath, 'utf8');
  stats.bundleBytes = Buffer.byteLength(html, 'utf8');
  stats.bundleKB = Math.round(stats.bundleBytes / 1024);
  stats.bundleLines = html.split('\n').length;
}

const generatedSource = `// Auto-generated by scripts/gen-stats.js. Do not edit by hand.
const MEDCHECK_STATS = ${JSON.stringify(stats, null, 2)};
`;
writeFileSync(resolve(root, 'src/data/generatedStats.js'), generatedSource, 'utf8');

const readmePath = resolve(root, 'README.md');
const readme = readFileSync(readmePath, 'utf8');
const start = '<!-- MEDCHECK_STATS_START -->';
const end = '<!-- MEDCHECK_STATS_END -->';
const statsBlock = `${start}
- **${stats.drugs} drugs** in DRUG_DB
- **${stats.studies} evidence entries** in STUDY_DB (${stats.studiesWithPmid} with PMIDs)${stats.reviewQueue ? ` — **${stats.verifiedStudies} verified**, **${stats.reviewQueue} quarantined enrichment drafts** awaiting human review` : ''}
- **${stats.ddiPairs} curated DDI pairs** (${stats.severeDdi} severe, ${stats.moderateDdi} moderate, ${stats.mildDdi} mild)
- **${stats.genotypeGenes} genotype genes**, **${stats.metaboliteEntries} curated metabolite entries** across **${stats.metaboliteParents} parent substances**, **${stats.metaboliteActors} first-class metabolite actors**, **${stats.receptorScores} receptor score profiles**
- **${stats.beersFlags} Beers flags** and **${stats.washoutRules} washout rules**
- **${stats.bundleKB || 'Not yet built'} KB** generated bundle${stats.bundleLines ? ` (${stats.bundleLines} lines)` : ''}
${end}`;

let nextReadme;
if (readme.includes(start) && readme.includes(end)) {
  nextReadme = readme.replace(new RegExp(`${start}[\\s\\S]*?${end}`), statsBlock);
} else {
  nextReadme = readme.replace(
    '---\n\n## Features',
    `---\n\n## Live Source Stats\n\n${statsBlock}\n\n---\n\n## Features`
  );
}
writeFileSync(readmePath, nextReadme, 'utf8');

process.stdout.write(`Generated stats: ${stats.drugs} drugs, ${stats.studies} studies, ${stats.ddiPairs} DDI pairs\n`);
